version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:6
    container_name: laas-calculator-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - laas-network

  # MongoDB Express web-based admin interface (optional)
  mongo-express:
    image: mongo-express
    container_name: laas-calculator-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongo:27017/
    depends_on:
      - mongo
    networks:
      - laas-network

  # Backend API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laas-calculator-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/laas-calculator?authSource=admin
      JWT_SECRET: your_jwt_secret_change_in_production
      JWT_EXPIRE: 30d
    depends_on:
      - mongo
    networks:
      - laas-network

networks:
  laas-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
